### PR TITLE
added ADR for uning pandas and cookie cutter

### PR DESCRIPTION
**Pull request by laalsanedo**

### CODE REVIEW

**Comment by letian0102** [comment]
Seems like you have two panda adr files? Is that a mistake or?

**Comment by liavcueto375** [comment]
I concur with Tian - I see two copies of the same Pandas ADR currently.

**Comment by laalsanedo** [comment]
Sorry about that guys.. please see the updated one

**Comment by liavcueto375** [comment]
Looks good to me!

**Pull request merged**
